<!-- 
    Promises stages - 
        Pending
        Resolve
        Reject
 -->

 <script>
     const promiseObj1 = new Promise( (resolve, reject) => {

         setTimeout(() => {
             let roll_no = [1,2,3,4,5];
             resolve(roll_no);
             reject("Error while calling API");
         }, 2000);

     });

     const getBiodata = (rollno) => {
         return new Promise( (resolve, reject) => {
            setTimeout((indexdata) => {
                let bioData = {
                    name: 'Navin',
                    age: 34
                }
                resolve( `My roll no is ${indexdata} and my name is ${bioData.name} and I am ${bioData.age} years old`);
            }, 2000, rollno);
         } );
     }

    promiseObj1.then( (rollno) => {
        console.log(rollno);
        return getBiodata(rollno[1]);
    }).then( (test) => {
            console.log(test);
    }).catch( (error) => {
        console.log(error);
    });
 </script>